const basketItems = {
  item1: {
    name: 'White-tailed deer',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: 'Hello hello this is an example',
    price: '$3.45',
    size: 'XL',
    status: 'XAF',
  },
  item2: {
    name: 'European badger',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: 'Such a cool shirt',
    price: '$0.25',
    size: 'XS',
    status: 'CNY',
  },
  item3: {
    name: 'Loris, not slender, really fat.',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: '‪‪test‪',
    price: '$2.82',
    size: 'L',
    status: 'EUR',
  },
  item4: {
    name: 'White-browed owl',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: '-JKLASDJKASKDJAKL:SJDjajsdjajsdjasd',
    price: '$1.30',
    size: 'XS',
    status: 'EUR',
  },
  item5: {
    name: 'Coatimundi, ring-tailed',
    image: 'https://source.unsplash.com/300x300/?bicycles`',
    desc: 'LOrem Ipsum yo',
    price: '$8.30',
    size: 'M',
    status: 'UAH',
  },
  item6: {
    name: 'Black swan',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: ':D :D :D :D :D :)',
    price: '$7.82',
    size: '3XL',
    status: 'BAM',
  },
  item7: {
    name: 'Test',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: 'Hello hello',
    price: '$7.82',
    size: '3XL',
    status: 'BAM',
  },
  item8: {
    name: 'Test',
    image: 'https://source.unsplash.com/300x300/?fashion,clothing',
    desc: 'Hello hello',
    price: '$7.82',
    size: '3XL',
    status: 'BAM',
  },
}
export default basketItems
